class NaaccrItem < ActiveRecord::Base
# class NaaccrItem < ApplicationRecord
  has_many :naaccr_item_codes
  has_many :naaccr_schema_maps, as: :mappable
  belongs_to :naaccr_version

  SECTION_CANCER_IDENTIFICATION = 'Cancer Identification'
  SECTION_DEMOGRAPHIC = 'Demographic'
  SECTION_EDIT_OVERRIDES_CONVERSION_HISTORY_SYSTEM_ADMIN = 'Edit Overrides/Conversion History/System Admin'
  SECTION_FOLLOW_UP_RECURRENCE_DEATH = 'Follow-up/Recurrence/Death'
  SECTION_HOSPITAL_CONFIDENTIAL = 'Hospital-Confidential'
  SECTION_HOSPITAL_SPECIFIC = 'Hospital-Specific'
  SECTION_OTHER_CONFIDENTIAL = 'Other-Confidential'
  SECTION_PATHOLOGY = 'Pathology'
  SECTION_PATIENT_CONFIDENTIAL = 'Patient-Confidential'
  SECTION_RECORD_ID = 'Record ID'
  SECTION_SPECIAL_USE = 'Special Use'
  STAGE_PROGNOSTIC_FACTORS = 'Stage/Prognostic Factors'
  SECTION_TEXT_DIAGNOSIS = 'Text-Diagnosis'
  SECTION_TEXT_MISCELLANEOUS = 'Text-Miscellaneous'
  SECTION_TEXT_TREATMENT = 'Text-Treatment'
  SECTION_TREATMENT_1ST_COURSE = 'Treatment-1st Course'
  SECTION_TREATMENT_SUBSEQUENT_AND_OTHER = 'Treatment-Subsequent & Other'

  SECTIONS = [SECTION_CANCER_IDENTIFICATION, SECTION_DEMOGRAPHIC, SECTION_EDIT_OVERRIDES_CONVERSION_HISTORY_SYSTEM_ADMIN, SECTION_FOLLOW_UP_RECURRENCE_DEATH, SECTION_HOSPITAL_CONFIDENTIAL, SECTION_HOSPITAL_SPECIFIC, SECTION_OTHER_CONFIDENTIAL, SECTION_PATHOLOGY, SECTION_PATIENT_CONFIDENTIAL, SECTION_RECORD_ID, SECTION_SPECIAL_USE, STAGE_PROGNOSTIC_FACTORS, SECTION_TEXT_DIAGNOSIS, SECTION_TEXT_MISCELLANEOUS, SECTION_TEXT_TREATMENT, SECTION_TREATMENT_1ST_COURSE, SECTION_TREATMENT_SUBSEQUENT_AND_OTHER]
  RELEVANT_SECTIONS = [SECTION_CANCER_IDENTIFICATION, STAGE_PROGNOSTIC_FACTORS, SECTION_TREATMENT_1ST_COURSE, SECTION_FOLLOW_UP_RECURRENCE_DEATH]

  NOTE_NEW = 'New'
  NOTE_RETIRED = 'Retired'
  NOTES = [NOTE_NEW, NOTE_RETIRED]

  ITEM_OMOP_DOMAIN_ID_NONE = 'None'
  ITEM_OMOP_DOMAIN_ID_MEASUREMENT = 'Measurement'
  ITEM_OMOP_DOMAIN_ID_EPISODE = 'Episode'
  ITEM_OMOP_DOMAIN_IDS = [ITEM_OMOP_DOMAIN_ID_NONE, ITEM_OMOP_DOMAIN_ID_MEASUREMENT, ITEM_OMOP_DOMAIN_ID_EPISODE]

  SITE_SPECIFIC_STATUS_SITE_INDEPENDENT = 'Site-independent'
  SITE_SPECIFIC_STATUS_SITE_SPECIFIC = 'Site-specific'
end