source('functions/plot_functions.R')

## Loading Test Data
TEST_DATA <- read.csv("data/test_data.csv")

## Generating Plots: 
## Once running the test plots on the test data, 
## Please take the data generated by the SQL scripts and replace TEST_DATA 
## with the name of the R object of your own data. The remainder of the
## arguments do not need to be changed if it is a raw input from the SQL script.

plot_survival(native_dataframe  = TEST_DATA,
              survival_time_col = survival_from_diagnosis_months, 
              event_col         = vital_status,
              cohort_col        = cancer_type) 


plot_time_to_rx_hist(native_dataframe = TEST_DATA, 
                     target_value_col = time_daignosis_treatment_days, 
                     cohort_col = cancer_type)
