SET search_path TO omop, public;

DROP TABLE IF EXISTS naaccr_items;
CREATE TABLE naaccr_items(
  item_number                  varchar(255) NULL,
  item_name                    varchar(255) NULL,
  section                      varchar(255) NULL
);

TRUNCATE TABLE naaccr_items;

INSERT INTO naaccr_items (item_number, item_name, section) SELECT '380', 'Sequence Number--Central', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '390', 'Date of Diagnosis', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '391', 'Date of Diagnosis Flag', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '400', 'Primary Site', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '410', 'Laterality', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '419', 'Morph--Type&Behav ICD-O-2', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '420', 'Histology (92-00) ICD-O-2', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '430', 'Behavior (92-00) ICD-O-2', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '439', 'Date of Mult Tumors Flag', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '440', 'Grade', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '441', 'Grade Path Value', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '442', 'Ambiguous Terminology DX', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '443', 'Date Conclusive DX', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '444', 'Mult Tum Rpt as One Prim', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '445', 'Date of Mult Tumors', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '446', 'Multiplicity Counter', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '448', 'Date Conclusive DX Flag', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '449', 'Grade Path System', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '450', 'Site Coding Sys--Current', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '460', 'Site Coding Sys--Original', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '470', 'Morph Coding Sys--Current', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '480', 'Morph Coding Sys--Originl', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '490', 'Diagnostic Confirmation', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '500', 'Type of Reporting Source', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '501', 'Casefinding Source', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '521', 'Morph--Type&Behav ICD-O-3', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '522', 'Histologic Type ICD-O-3', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '523', 'Behavior Code ICD-O-3', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '680', 'Reserved 03', 'Cancer Identification';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1740', 'Reserved 09', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1750', 'Date of Last Contact', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1751', 'Date of Last Contact Flag', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1755', 'Date of Death--Canada', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1756', 'Date of Death--CanadaFlag', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1760', 'Vital Status', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1762', 'Vital Status Recode', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1770', 'Cancer Status', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1772', 'Date of Last Cancer (tumor) Status ', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1773', 'Date of Last Cancer (tumor) Status Flag', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1775', 'Record Number Recode', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1780', 'Quality of Survival', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1782', 'Surv-Date Active Followup', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1783', 'Surv-Flag Active Followup', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1784', 'Surv-Mos Active Followup', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1785', 'Surv-Date Presumed Alive', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1786', 'Surv-Flag Presumed Alive', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1787', 'Surv-Mos Presumed Alive', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1788', 'Surv-Date DX Recode', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1790', 'Follow-Up Source', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1791', 'Follow-up Source Central', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1800', 'Next Follow-Up Source', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1810', 'Addr Current--City', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1820', 'Addr Current--State', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1830', 'Addr Current--Postal Code', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1840', 'County--Current', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1842', 'Follow-Up Contact--City', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1844', 'Follow-Up Contact--State', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1846', 'Follow-Up Contact--Postal', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1850', 'Unusual Follow-Up Method', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1860', 'Recurrence Date--1st', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1861', 'Recurrence Date--1st Flag', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1880', 'Recurrence Type--1st', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1910', 'Cause of Death', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1914', 'SEER Cause Specific COD', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1915', 'SEER Other COD', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1920', 'ICD Revision Number', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1930', 'Autopsy', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1940', 'Place of Death', 'Follow-up/Recurrence/Death';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '682', 'Date Regional Lymph Node Dissection', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '683', 'Date Regional Lymph Node Dissection Flag', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '752', 'Tumor Size Clinical', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '754', 'Tumor Size Pathologic', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '756', 'Tumor Size Summary', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '759', 'SEER Summary Stage 2000', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '760', 'SEER Summary Stage 1977', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '762', 'Derived Summary Stage 2018', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '764', 'Summary Stage 2018', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '772', 'EOD Primary Tumor', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '774', 'EOD Regional Nodes', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '776', 'EOD Mets', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '779', 'Extent of Disease 10-Dig', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '780', 'EOD--Tumor Size', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '785', 'Derived EOD 2018 T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '790', 'EOD--Extension', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '795', 'Derived EOD 2018 M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '800', 'EOD--Extension Prost Path', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '810', 'EOD--Lymph Node Involv', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '815', 'Derived EOD 2018 N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '818', 'Derived EOD 2018 Stage Group', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '820', 'Regional Nodes Positive', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '830', 'Regional Nodes Examined', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '832', 'Date of Sentinel Lymph Node Biopsy', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '833', 'Date of Sentinel Lymph Node Biopsy Flag', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '834', 'Sentinel Lymph Nodes Examined', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '835', 'Sentinel Lymph Nodes Positive', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '840', 'EOD--Old 13 Digit', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '850', 'EOD--Old 2 Digit', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '860', 'EOD--Old 4 Digit', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '870', 'Coding System for EOD', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '880', 'TNM Path T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '890', 'TNM Path N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '900', 'TNM Path M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '910', 'TNM Path Stage Group', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '920', 'TNM Path Descriptor', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '930', 'TNM Path Staged By', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '940', 'TNM Clin T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '950', 'TNM Clin N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '960', 'TNM Clin M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '970', 'TNM Clin Stage Group', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '980', 'TNM Clin Descriptor', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '990', 'TNM Clin Staged By', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '995', 'AJCC ID', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1001', 'AJCC TNM Clin T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1002', 'AJCC TNM Clin N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1003', 'AJCC TNM Clin M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1004', 'AJCC TNM Clin Stage Group', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1011', 'AJCC TNM Path T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1012', 'AJCC TNM Path N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1013', 'AJCC TNM Path M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1014', 'AJCC TNM Path Stage Group', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1021', 'AJCC TNM Post Therapy T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1022', 'AJCC TNM Post Therapy N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1023', 'AJCC TNM Post Therapy M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1024', 'AJCC TNM Post Therapy Stage Group', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1031', 'AJCC TNM Clin T Suffix', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1032', 'AJCC TNM Path T Suffix', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1033', 'AJCC TNM Post Therapy T Suffix', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1034', 'AJCC TNM Clin N Suffix', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1035', 'AJCC TNM Path N Suffix', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1036', 'AJCC TNM Post Therapy N Suffix', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1060', 'TNM Edition Number', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1112', 'Mets at DX-Bone', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1113', 'Mets at DX-Brain', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1114', 'Mets at Dx-Distant LN', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1115', 'Mets at DX-Liver', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1116', 'Mets at DX-Lung', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1117', 'Mets at DX-Other', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1120', 'Pediatric Stage', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1130', 'Pediatric Staging System', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1140', 'Pediatric Staged By', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1150', 'Tumor Marker 1', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1160', 'Tumor Marker 2', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1170', 'Tumor Marker 3', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1180', 'Reserved 05', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1182', 'Lymphovascular Invasion', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2400', 'Reserved 15', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2800', 'CS Tumor Size', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2810', 'CS Extension', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2820', 'CS Tumor Size/Ext Eval', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2830', 'CS Lymph Nodes', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2840', 'CS Lymph Nodes Eval', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2850', 'CS Mets at DX', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2851', 'CS Mets at Dx-Bone', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2852', 'CS Mets at Dx-Brain', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2853', 'CS Mets at Dx-Liver', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2854', 'CS Mets at Dx-Lung', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2860', 'CS Mets Eval', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2861', 'CS Site-Specific Factor 7', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2862', 'CS Site-Specific Factor 8', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2863', 'CS Site-Specific Factor 9', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2864', 'CS Site-Specific Factor10', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2865', 'CS Site-Specific Factor11', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2866', 'CS Site-Specific Factor12', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2867', 'CS Site-Specific Factor13', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2868', 'CS Site-Specific Factor14', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2869', 'CS Site-Specific Factor15', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2870', 'CS Site-Specific Factor16', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2871', 'CS Site-Specific Factor17', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2872', 'CS Site-Specific Factor18', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2873', 'CS Site-Specific Factor19', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2874', 'CS Site-Specific Factor20', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2875', 'CS Site-Specific Factor21', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2876', 'CS Site-Specific Factor22', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2877', 'CS Site-Specific Factor23', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2878', 'CS Site-Specific Factor24', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2879', 'CS Site-Specific Factor25', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2880', 'CS Site-Specific Factor 1', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2890', 'CS Site-Specific Factor 2', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2900', 'CS Site-Specific Factor 3', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2910', 'CS Site-Specific Factor 4', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2920', 'CS Site-Specific Factor 5', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2930', 'CS Site-Specific Factor 6', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2935', 'CS Version Input Original', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2936', 'CS Version Derived', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2937', 'CS Version Input Current', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2940', 'Derived AJCC-6 T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2950', 'Derived AJCC-6 T Descript', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2960', 'Derived AJCC-6 N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2970', 'Derived AJCC-6 N Descript', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2980', 'Derived AJCC-6 M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '2990', 'Derived AJCC-6 M Descript', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3000', 'Derived AJCC-6 Stage Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3010', 'Derived SS1977', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3020', 'Derived SS2000', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3030', 'Derived AJCC--Flag', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3040', 'Derived SS1977--Flag', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3050', 'Derived SS2000--Flag', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3110', 'Comorbid/Complication 1', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3120', 'Comorbid/Complication 2', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3130', 'Comorbid/Complication 3', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3140', 'Comorbid/Complication 4', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3150', 'Comorbid/Complication 5', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3160', 'Comorbid/Complication 6', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3161', 'Comorbid/Complication 7', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3162', 'Comorbid/Complication 8', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3163', 'Comorbid/Complication 9', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3164', 'Comorbid/Complication 10', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3165', 'ICD Revision Comorbid', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3400', 'Derived AJCC-7 T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3402', 'Derived AJCC-7 T Descript', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3410', 'Derived AJCC-7 N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3412', 'Derived AJCC-7 N Descript', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3420', 'Derived AJCC-7 M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3422', 'Derived AJCC-7 M Descript', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3430', 'Derived AJCC-7 Stage Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3440', 'Derived PreRx-7 T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3442', 'Derived PreRx-7 T Descrip', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3450', 'Derived PreRx-7 N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3452', 'Derived PreRx-7 N Descrip', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3460', 'Derived PreRx-7 M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3462', 'Derived PreRx-7 M Descrip', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3470', 'Derived PreRx-7 Stage Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3480', 'Derived PostRx-7 T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3482', 'Derived PostRx-7 N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3490', 'Derived PostRx-7 M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3492', 'Derived PostRx-7 Stge Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3600', 'Derived Neoadjuv Rx Flag', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3605', 'Derived SEER Path Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3610', 'Derived SEER Clin Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3614', 'Derived SEER Cmb Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3616', 'Derived SEER Combined T', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3618', 'Derived SEER Combined N', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3620', 'Derived SEER Combined M', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3622', 'Derived SEER Cmb T Src', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3624', 'Derived SEER Cmb N Src', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3626', 'Derived SEER Cmb M Src', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3645', 'NPCR Derived AJCC 8 TNM Clin Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3646', 'NPCR Derived AJCC 8 TNM Path Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3647', 'NPCR Derived AJCC 8 TNM Post Therapy Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3650', 'NPCR Derived Clin Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3655', 'NPCR Derived Path Stg Grp', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3700', 'SEER Site-Specific Fact 1', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3702', 'SEER Site-Specific Fact 2', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3704', 'SEER Site-Specific Fact 3', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3706', 'SEER Site-Specific Fact 4', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3708', 'SEER Site-Specific Fact 5', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3710', 'SEER Site-Specific Fact 6', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3720', 'NPCR Specific Field', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3780', 'Secondary Diagnosis 1', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3782', 'Secondary Diagnosis 2', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3784', 'Secondary Diagnosis 3', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3786', 'Secondary Diagnosis 4', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3788', 'Secondary Diagnosis 5', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3790', 'Secondary Diagnosis 6', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3792', 'Secondary Diagnosis 7', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3794', 'Secondary Diagnosis 8', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3796', 'Secondary Diagnosis 9', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3798', 'Secondary Diagnosis 10', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3800', 'Schema ID', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3801', 'Chromosome 1p: Loss of Heterozygosity (LOH)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3802', 'Chromosome 19q: Loss of Heterozygosity (LOH)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3803', 'Adenoid Cystic Basaloid Pattern', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3804', 'Adenopathy', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3805', 'AFP Post-Orchiectomy Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3806', 'AFP Post-Orchiectomy Range', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3807', 'AFP Pre-Orchiectomy Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3808', 'AFP Pre-Orchiectomy Range', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3809', 'AFP Pretreatment Interpretation', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3810', 'AFP Pretreatment Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3811', 'Anemia', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3812', 'B symptoms', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3813', 'Bilirubin Pretreatment Total Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3814', 'Bilirubin Pretreatment Unit of Measure', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3815', 'Bone Invasion', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3816', 'Brain Molecular Markers', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3817', 'Breslow Tumor Thickness ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3818', 'CA-125 Pretreatment Interpretation', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3819', 'CEA Pretreatment Interpretation', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3820', 'CEA Pretreatment Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3821', 'Chromosome 3 Status', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3822', 'Chromosome 8q Status', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3823', 'Circumferential Resection Margin (CRM)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3824', 'Creatinine Pretreatment Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3825', 'Creatinine Pretreatment Unit of Measure', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3826', 'Estrogen Receptor Percent Positive or Range ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3827', 'Estrogen Receptor Summary', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3828', 'Estrogen Receptor Total Allred Score ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3829', 'Esophagus and EGJ Tumor Epicenter', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3830', 'Extranodal Extension Clin (non-Head and Neck)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3831', 'Extranodal Extension Head and Neck Clinical', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3832', 'Extranodal Extension Head and Neck Pathological', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3833', 'Extranodal Extension Path (non-Head and Neck)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3834', 'Extravascular Matrix Patterns ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3835', 'Fibrosis Score', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3836', 'FIGO Stage', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3837', 'Gestational Trophoblastic Prognostic Scoring Index', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3838', 'Gleason Patterns Clinical', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3839', 'Gleason Patterns Pathological', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3840', 'Gleason Score Clinical', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3841', 'Gleason Score Pathological', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3842', 'Gleason Tertiary Pattern', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3843', 'Grade Clinical', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3844', 'Grade Pathological', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3845', 'Grade Post Therapy', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3846', 'hCG Post-Orchiectomy Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3847', 'hCG Post-Orchiectomy Range', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3848', 'hCG Pre-Orchiectomy Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3849', 'hCG Pre-Orchiectomy Range', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3850', 'HER2 IHC Summary ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3851', 'HER2 ISH Dual Probe Copy Number', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3852', 'HER2 ISH Dual Probe Ratio', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3853', 'HER2 ISH Single Probe Copy Number', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3854', 'HER2 ISH Summary', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3855', 'HER2 Overall Summary ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3856', 'Heritable Trait', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3857', 'High Risk Cytogenetics', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3858', 'High Risk Histologic Features', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3859', 'HIV Status', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3860', 'International Normalized Ratio Prothrombin Time', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3861', 'Ipsilateral Adrenal Gland Involvement', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3862', 'JAK2', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3863', 'Ki-67', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3864', 'Invasion Beyond Capsule', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3865', 'KIT Gene Immunohistochemistry ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3866', 'KRAS', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3867', 'LDH Post-Orchiectomy Range', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3868', 'LDH Pre-Orchiectomy Range', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3869', 'LDH Pretreatment Level', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3870', 'LDH Upper Limits of Normal', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3871', 'LN Assessment Method Femoral-Inguinal', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3872', 'LN Assessment Method Para-Aortic', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3873', 'LN Assessment Method Pelvic', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3874', 'LN Distant Assessment Method', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3875', 'LN Distant: Mediastinal  Scalene', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3876', 'LN Head and Neck Levels I-III', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3877', 'LN Head and Neck Levels IV-V', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3878', 'LN Head and Neck Levels VI-VII', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3879', 'LN Head and Neck Other', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3880', 'LN Isolated Tumor Cells (ITC)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3881', 'LN Laterality', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3882', 'LN Positive Axillary Level I-II', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3883', 'LN Size', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3884', 'LN Status Femoral-Inguinal  Para-Aortic  Pelvic', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3885', 'Lymphocytosis', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3886', 'Major Vein Involvement', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3887', 'Measured Basal Diameter', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3888', 'Measured Thickness', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3889', 'Methylation of O6-Methylguanine-Methyltransferase', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3890', 'Microsatellite Instability (MSI)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3891', 'Microvascular Density ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3892', 'Mitotic Count Uveal Melanoma', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3893', 'Mitotic Rate Melanoma', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3894', 'Multigene Signature Method', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3895', 'Multigene Signature Results', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3896', 'NCCN International Prognostic Index (IPI)', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3897', 'Number of Cores Examined', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3898', 'Number of Cores Positive', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3899', 'Number of Examined Para-Aortic Nodes', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3900', 'Number of Examined Pelvic Nodes', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3901', 'Number of Positive Para-Aortic Nodes', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3902', 'Number of Positive Pelvic Nodes', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3903', 'Oncotype Dx Recurrence Score-DCIS', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3904', 'Oncotype Dx Recurrence Score-Invasive', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3905', 'Oncotype Dx Risk Level-DCIS', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3906', 'Oncotype Dx Risk Level-Invasive', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3907', 'Organomegaly', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3908', 'Percent Necrosis Post Neoadjuvant', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3909', 'Perineural Invasion', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3910', 'Peripheral Blood Involvement', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3911', 'Peritoneal Cytology', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3913', 'Pleural Effusion', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3914', 'Progesterone Receptor Percent Positive or Range', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3915', 'Progesterone Receptor Summary', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3916', 'Progesterone Receptor Total Allred Score', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3917', 'Primary Sclerosing Cholangitis ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3918', 'Profound Immune Suppression', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3919', 'Prostate Pathological Extension', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3920', 'PSA (Prostatic Specific Antigen) Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3921', 'Residual Tumor Volume Post Cytoreduction ', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3922', 'Response to Neoadjuvant Therapy', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3923', 'S Category Clinical', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3924', 'S Category Pathological', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3925', 'Sarcomatoid Features', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3926', 'Schema Discriminator 1', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3927', 'Schema Discriminator 2', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3928', 'Schema Discriminator 3', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3929', 'Separate Tumor Nodules', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3930', 'Serum Albumin Pretreatment Level', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3931', 'Serum Beta-2 Microglobulin Pretreatment Level', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3932', 'LDH Pretreatment Lab Value', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3933', 'Thrombocytopenia', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3934', 'Tumor Deposits', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3935', 'Tumor Growth Pattern', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3936', 'Ulceration', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3937', 'Visceral and Parietal Pleural Invasion', 'Stage/Prognostic Factors';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1190', 'Reserved 06', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1200', 'RX Date Surgery', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1201', 'RX Date Surgery Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1210', 'RX Date Radiation', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1211', 'RX Date Radiation Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1220', 'RX Date Chemo', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1221', 'RX Date Chemo Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1230', 'RX Date Hormone', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1231', 'RX Date Hormone Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1240', 'RX Date BRM', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1241', 'RX Date BRM Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1250', 'RX Date Other', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1251', 'RX Date Other Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1260', 'Date Initial RX SEER', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1261', 'Date Initial RX SEER Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1270', 'Date 1st Crs RX CoC', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1271', 'Date 1st Crs RX CoC Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1280', 'RX Date DX/Stg Proc', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1281', 'RX Date DX/Stg Proc Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1285', 'RX Summ--Treatment Status', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1290', 'RX Summ--Surg Prim Site', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1292', 'RX Summ--Scope Reg LN Sur', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1294', 'RX Summ--Surg Oth Reg/Dis', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1296', 'RX Summ--Reg LN Examined', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1310', 'RX Summ--Surgical Approch', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1320', 'RX Summ--Surgical Margins', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1330', 'RX Summ--Reconstruct 1st', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1340', 'Reason for No Surgery', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1350', 'RX Summ--DX/Stg Proc', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1360', 'RX Summ--Radiation', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1370', 'RX Summ--Rad to CNS', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1380', 'RX Summ--Surg/Rad Seq', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1390', 'RX Summ--Chemo', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1400', 'RX Summ--Hormone', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1410', 'RX Summ--BRM', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1420', 'RX Summ--Other', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1430', 'Reason for No Radiation', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1460', 'RX Coding System--Current', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1501', 'Phase I Dose per Fraction', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1502', 'Phase I Radiation External Beam Planning Tech', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1503', 'Phase I Number of Fractions', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1504', 'Phase I Radiation Primary Treatment Volume', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1505', 'Phase I Radiation to Draining Lymph Nodes', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1506', 'Phase I Radiation Treatment Modality', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1507', 'Phase I Total Dose', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1510', 'Rad--Regional Dose: cGy', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1511', 'Phase II Dose per Fraction', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1512', 'Phase II Radiation External Beam Planning Tech', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1513', 'Phase II Number of Fractions', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1514', 'Phase II Radiation Primary Treatment Volume', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1515', 'Phase II Radiation to Draining Lymph Nodes', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1516', 'Phase II Radiation Treatment Modality', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1517', 'Phase II Total Dose', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1520', 'Rad--No of Treatment Vol', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1521', 'Phase III Dose per Fraction', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1522', 'Phase III Radiation External Beam Planning Tech', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1523', 'Phase III Number of Fractions', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1524', 'Phase III Radiation Primary Treatment Volume', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1525', 'Phase III Radiation to Draining Lymph Nodes', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1526', 'Phase III Radiation Treatment Modality', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1527', 'Phase III Total Dose', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1531', 'Radiation Treatment Discontinued Early', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1532', 'Number of Phases of Rad Treatment to this Volume', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1533', 'Total Dose', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1540', 'Rad--Treatment Volume', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1550', 'Rad--Location of RX', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1570', 'Rad--Regional RX Modality', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1639', 'RX Summ--Systemic/Sur Seq', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1640', 'RX Summ--Surgery Type', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1646', 'RX Summ--Surg Site 98-02', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1647', 'RX Summ--Scope Reg 98-02', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '1648', 'RX Summ--Surg Oth 98-02', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3170', 'RX Date Mst Defn Srg', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3171', 'RX Date Mst Defn Srg Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3180', 'RX Date Surg Disch', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3181', 'RX Date Surg Disch Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3190', 'Readm Same Hosp 30 Days', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3200', 'Rad--Boost RX Modality', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3210', 'Rad--Boost Dose cGy', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3220', 'RX Date Rad Ended', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3221', 'RX Date Rad Ended Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3230', 'RX Date Systemic', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3231', 'RX Date Systemic Flag', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3250', 'RX Summ--Transplnt/Endocr', 'Treatment-1st Course';
INSERT INTO naaccr_items (item_number, item_name, section) SELECT '3270', 'RX Summ--Palliative Proc', 'Treatment-1st Course';


-- select *
-- from naaccr_data_points ndp join naaccr_items ni ON ndp.naaccr_item_number = ni.item_number
-- where record_id = '?'
-- and naaccr_item_value is not null
-- and  section != 'Follow-up/Recurrence/Death'
-- order by item_name
